name: lojateamodas
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  url_strategy: ^0.2.0
  mask_text_input_formatter: ^2.4.0
  badges: ^2.0.3
  intl: ^0.17.0
  get: ^4.6.5
  fluttertoast: ^8.1.1
  shimmer: ^2.0.0
  dio: ^4.0.6
  
  json_annotation: ^4.7.0
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  flutter_secure_storage: ^6.0.0
  clipboard: ^0.1.3
  firebase_messaging: ^14.1.2
  alphabet_list_scroll_view: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_core: ^2.4.0
  another_flushbar: ^1.12.29
  flip_card: ^0.6.0
  brasil_fields: ^1.9.0
  credit_card_type_detector: ^2.0.0
  http: ^0.13.5
  
  
  cpf_cnpj_validator: ^2.0.0
  cloud_firestore: ^4.3.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2



  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pix.png
    - assets/images/chipcartao.png



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 

flutter_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
  
