// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOlnxd6SbQiegjFZ7Y238e9PVYKU_eauU',
    appId: '1:394552781816:web:4da93ebd345ba846c3440d',
    messagingSenderId: '394552781816',
    projectId: 'teamodafeminina-1a688',
    authDomain: 'teamodafeminina-1a688.firebaseapp.com',
    databaseURL: 'https://teamodafeminina-1a688-default-rtdb.firebaseio.com',
    storageBucket: 'teamodafeminina-1a688.appspot.com',
    measurementId: 'G-5JD42KGH13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMnYRCWwVWbh1L8vSSWMSLLlV9FDKySY',
    appId: '1:394552781816:android:7700253d49246675c3440d',
    messagingSenderId: '394552781816',
    projectId: 'teamodafeminina-1a688',
    databaseURL: 'https://teamodafeminina-1a688-default-rtdb.firebaseio.com',
    storageBucket: 'teamodafeminina-1a688.appspot.com',
  );
}
